INSERT INTO "Port" (
  "id",
  "portCode",
  "portName",
  "country",
  "countryName",
  "region",
  "latitude",
  "longitude",
  "portType",
  "defaultServices",
  "avgTurnaroundHours",
  "createdAt",
  "updatedAt"
) VALUES
  ('port_alias_MUNDRA', 'MUNDRA', 'Mundra', 'IN', 'India', 'INDIAN_SUBCONTINENT', 22.74, 69.71, ARRAY['COMMERCIAL', 'CONTAINER'], ARRAY['Port agency', 'Bulk cargo', 'Container logistics'], 36, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('port_alias_VISAKHAPATNAM', 'VISAKHAPATNAM', 'Visakhapatnam', 'IN', 'India', 'INDIAN_SUBCONTINENT', 17.69, 83.29, ARRAY['COMMERCIAL', 'BULK'], ARRAY['Bulk cargo', 'Hold cleaning', 'Port agency'], 36, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('port_alias_SIKKA', 'SIKKA', 'Sikka', 'IN', 'India', 'INDIAN_SUBCONTINENT', 22.43, 69.82, ARRAY['COMMERCIAL', 'BULK'], ARRAY['Bulk cargo', 'Port agency', 'Port logistics'], 36, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('port_alias_NHAVASHEVA', 'NHAVASHEVA', 'Nhava Sheva / JNPT', 'IN', 'India', 'INDIAN_SUBCONTINENT', 18.95, 72.95, ARRAY['COMMERCIAL', 'CONTAINER'], ARRAY['Container logistics', 'Port agency', 'Port logistics'], 36, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('port_alias_HAZIRA', 'HAZIRA', 'Hazira', 'IN', 'India', 'INDIAN_SUBCONTINENT', 21.11, 72.65, ARRAY['COMMERCIAL'], ARRAY['Port agency', 'Bulk cargo', 'Port logistics'], 36, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('port_alias_DAHEJ', 'DAHEJ', 'Dahej', 'IN', 'India', 'INDIAN_SUBCONTINENT', 21.70, 72.54, ARRAY['COMMERCIAL', 'BULK'], ARRAY['Bulk cargo', 'Port agency', 'Port logistics'], 36, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('port_alias_PARADIP', 'PARADIP', 'Paradip', 'IN', 'India', 'INDIAN_SUBCONTINENT', 20.27, 86.68, ARRAY['COMMERCIAL', 'BULK'], ARRAY['Bulk cargo', 'Hold cleaning', 'Port agency'], 36, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('port_alias_MANGALORE', 'MANGALORE', 'New Mangalore', 'IN', 'India', 'INDIAN_SUBCONTINENT', 12.92, 74.81, ARRAY['COMMERCIAL'], ARRAY['Bulk cargo', 'Port agency', 'Port logistics'], 36, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('port_alias_KRISHNAPATNAM', 'KRISHNAPATNAM', 'Krishnapatnam', 'IN', 'India', 'INDIAN_SUBCONTINENT', 14.25, 80.12, ARRAY['COMMERCIAL', 'CONTAINER'], ARRAY['Port agency', 'Container logistics', 'Bulk cargo'], 36, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('port_alias_KOLKATA', 'KOLKATA', 'Kolkata', 'IN', 'India', 'INDIAN_SUBCONTINENT', 22.57, 88.36, ARRAY['COMMERCIAL'], ARRAY['River port agency', 'Bulk cargo', 'Port logistics'], 36, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('port_alias_MUMBAI', 'MUMBAI', 'Mumbai', 'IN', 'India', 'INDIAN_SUBCONTINENT', 18.95, 72.83, ARRAY['COMMERCIAL'], ARRAY['Ship agency', 'Crew change', 'Port logistics'], 36, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('port_alias_GANGAVARAM', 'GANGAVARAM', 'Gangavaram', 'IN', 'India', 'INDIAN_SUBCONTINENT', 17.62, 83.24, ARRAY['COMMERCIAL', 'BULK'], ARRAY['Bulk cargo', 'Port agency', 'Port logistics'], 36, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('port_alias_CHENNAI', 'CHENNAI', 'Chennai', 'IN', 'India', 'INDIAN_SUBCONTINENT', 13.08, 80.29, ARRAY['COMMERCIAL', 'CONTAINER'], ARRAY['Port agency', 'Crew change', 'Container logistics'], 36, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('port_alias_DHAMRA', 'DHAMRA', 'Dhamra', 'IN', 'India', 'INDIAN_SUBCONTINENT', 20.79, 86.95, ARRAY['COMMERCIAL', 'BULK'], ARRAY['Bulk cargo', 'Port agency', 'Port logistics'], 36, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('port_alias_DHAMARA', 'DHAMARA', 'Dhamra', 'IN', 'India', 'INDIAN_SUBCONTINENT', 20.79, 86.95, ARRAY['COMMERCIAL', 'BULK'], ARRAY['Bulk cargo', 'Port agency', 'Port logistics'], 36, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('port_alias_PIPAVAV', 'PIPAVAV', 'Pipavav', 'IN', 'India', 'INDIAN_SUBCONTINENT', 20.92, 71.51, ARRAY['COMMERCIAL', 'CONTAINER'], ARRAY['Port agency', 'Container logistics', 'Bulk cargo'], 36, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('port_alias_TUTICORIN', 'TUTICORIN', 'Tuticorin', 'IN', 'India', 'INDIAN_SUBCONTINENT', 8.75, 78.22, ARRAY['COMMERCIAL'], ARRAY['Port agency', 'Container logistics', 'Bulk cargo'], 36, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('port_alias_HALDIA', 'HALDIA', 'Haldia', 'IN', 'India', 'INDIAN_SUBCONTINENT', 22.03, 88.06, ARRAY['COMMERCIAL'], ARRAY['River port agency', 'Bulk cargo', 'Port logistics'], 36, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('port_alias_BEDI', 'BEDI', 'Bedi', 'IN', 'India', 'INDIAN_SUBCONTINENT', 22.50, 70.05, ARRAY['COMMERCIAL'], ARRAY['Port agency', 'Bulk cargo', 'Port logistics'], 36, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('port_alias_JAIGAD', 'JAIGAD', 'Jaigad', 'IN', 'India', 'INDIAN_SUBCONTINENT', 17.29, 73.22, ARRAY['COMMERCIAL'], ARRAY['Port agency', 'Bulk cargo', 'Port logistics'], 36, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('port_alias_ENNORE', 'ENNORE', 'Ennore / Kamarajar', 'IN', 'India', 'INDIAN_SUBCONTINENT', 13.25, 80.34, ARRAY['COMMERCIAL', 'BULK'], ARRAY['Bulk cargo', 'Port agency', 'Coal terminal services'], 36, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('port_alias_KAKINADA', 'KAKINADA', 'Kakinada', 'IN', 'India', 'INDIAN_SUBCONTINENT', 16.99, 82.28, ARRAY['COMMERCIAL'], ARRAY['Port agency', 'Bulk cargo', 'Port logistics'], 36, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('port_alias_VADINAR', 'VADINAR', 'Vadinar', 'IN', 'India', 'INDIAN_SUBCONTINENT', 22.47, 69.70, ARRAY['COMMERCIAL', 'BULK'], ARRAY['Bulk cargo', 'Port agency', 'Port logistics'], 36, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('port_alias_KARAIKAL', 'KARAIKAL', 'Karaikal', 'IN', 'India', 'INDIAN_SUBCONTINENT', 10.92, 79.84, ARRAY['COMMERCIAL'], ARRAY['Port agency', 'Bulk cargo', 'Port logistics'], 36, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('port_alias_MORMUGAO', 'MORMUGAO', 'Mormugao', 'IN', 'India', 'INDIAN_SUBCONTINENT', 15.41, 73.80, ARRAY['COMMERCIAL'], ARRAY['Bulk cargo', 'Ship agency', 'Port logistics'], 36, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('port_alias_CUDDALORE', 'CUDDALORE', 'Cuddalore', 'IN', 'India', 'INDIAN_SUBCONTINENT', 11.72, 79.77, ARRAY['COMMERCIAL'], ARRAY['Port agency', 'Bulk cargo', 'Port logistics'], 36, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('port_alias_SALAYA', 'SALAYA', 'Salaya', 'IN', 'India', 'INDIAN_SUBCONTINENT', 22.31, 69.60, ARRAY['COMMERCIAL', 'BULK'], ARRAY['Bulk cargo', 'Port agency', 'Port logistics'], 36, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('port_alias_KOCHI', 'KOCHI', 'Kochi', 'IN', 'India', 'INDIAN_SUBCONTINENT', 9.97, 76.24, ARRAY['COMMERCIAL'], ARRAY['Ship agency', 'Hull cleaning', 'Port logistics'], 36, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT ("portCode") DO UPDATE SET
  "portName" = EXCLUDED."portName",
  "country" = EXCLUDED."country",
  "countryName" = EXCLUDED."countryName",
  "region" = EXCLUDED."region",
  "latitude" = EXCLUDED."latitude",
  "longitude" = EXCLUDED."longitude",
  "portType" = EXCLUDED."portType",
  "defaultServices" = EXCLUDED."defaultServices",
  "avgTurnaroundHours" = COALESCE("Port"."avgTurnaroundHours", EXCLUDED."avgTurnaroundHours"),
  "updatedAt" = CURRENT_TIMESTAMP;
