INSERT INTO "Port" (
  "id",
  "portCode",
  "portName",
  "country",
  "countryName",
  "region",
  "latitude",
  "longitude",
  "portType",
  "defaultServices",
  "avgTurnaroundHours",
  "createdAt",
  "updatedAt"
) VALUES
  ('port_INKAN', 'INKAN', 'Kandla', 'IN', 'India', 'INDIAN_SUBCONTINENT', 23.03, 70.22, ARRAY['COMMERCIAL'], ARRAY['Port agency', 'OPA support', 'Hold cleaning'], 36, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('port_INBOM', 'INBOM', 'Mumbai', 'IN', 'India', 'INDIAN_SUBCONTINENT', 18.95, 72.83, ARRAY['COMMERCIAL'], ARRAY['Ship agency', 'Crew change', 'Port logistics'], 36, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('port_INNSA', 'INNSA', 'Nhava Sheva / JNPT', 'IN', 'India', 'INDIAN_SUBCONTINENT', 18.95, 72.95, ARRAY['COMMERCIAL', 'CONTAINER'], ARRAY['Container logistics', 'Port agency', 'Port logistics'], 36, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('port_INMUN', 'INMUN', 'Mundra', 'IN', 'India', 'INDIAN_SUBCONTINENT', 22.74, 69.71, ARRAY['COMMERCIAL', 'CONTAINER'], ARRAY['Port agency', 'Bulk cargo', 'Container logistics'], 36, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('port_INPAV', 'INPAV', 'Pipavav', 'IN', 'India', 'INDIAN_SUBCONTINENT', 20.92, 71.51, ARRAY['COMMERCIAL', 'CONTAINER'], ARRAY['Port agency', 'Container logistics', 'Bulk cargo'], 36, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('port_INMAA', 'INMAA', 'Chennai', 'IN', 'India', 'INDIAN_SUBCONTINENT', 13.08, 80.29, ARRAY['COMMERCIAL', 'CONTAINER'], ARRAY['Port agency', 'Crew change', 'Container logistics'], 36, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('port_INENR', 'INENR', 'Ennore / Kamarajar', 'IN', 'India', 'INDIAN_SUBCONTINENT', 13.25, 80.34, ARRAY['COMMERCIAL', 'BULK'], ARRAY['Bulk cargo', 'Port agency', 'Coal terminal services'], 36, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('port_INCOK', 'INCOK', 'Cochin', 'IN', 'India', 'INDIAN_SUBCONTINENT', 9.97, 76.24, ARRAY['COMMERCIAL'], ARRAY['Ship agency', 'Hull cleaning', 'Port logistics'], 36, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('port_INNML', 'INNML', 'New Mangalore', 'IN', 'India', 'INDIAN_SUBCONTINENT', 12.92, 74.81, ARRAY['COMMERCIAL'], ARRAY['Bulk cargo', 'Port agency', 'Port logistics'], 36, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('port_INMRM', 'INMRM', 'Mormugao', 'IN', 'India', 'INDIAN_SUBCONTINENT', 15.41, 73.8, ARRAY['COMMERCIAL'], ARRAY['Bulk cargo', 'Ship agency', 'Port logistics'], 36, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('port_INTUT', 'INTUT', 'Tuticorin', 'IN', 'India', 'INDIAN_SUBCONTINENT', 8.75, 78.22, ARRAY['COMMERCIAL'], ARRAY['Port agency', 'Container logistics', 'Bulk cargo'], 36, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('port_INVTZ', 'INVTZ', 'Visakhapatnam', 'IN', 'India', 'INDIAN_SUBCONTINENT', 17.69, 83.29, ARRAY['COMMERCIAL', 'BULK'], ARRAY['Bulk cargo', 'Hold cleaning', 'Port agency'], 36, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('port_INGGV', 'INGGV', 'Gangavaram', 'IN', 'India', 'INDIAN_SUBCONTINENT', 17.62, 83.24, ARRAY['COMMERCIAL', 'BULK'], ARRAY['Bulk cargo', 'Port agency', 'Port logistics'], 36, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('port_INPRT', 'INPRT', 'Paradip', 'IN', 'India', 'INDIAN_SUBCONTINENT', 20.27, 86.68, ARRAY['COMMERCIAL', 'BULK'], ARRAY['Bulk cargo', 'Hold cleaning', 'Port agency'], 36, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('port_INDHM', 'INDHM', 'Dhamra', 'IN', 'India', 'INDIAN_SUBCONTINENT', 20.79, 86.95, ARRAY['COMMERCIAL', 'BULK'], ARRAY['Bulk cargo', 'Port agency', 'Port logistics'], 36, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('port_INCCU', 'INCCU', 'Kolkata', 'IN', 'India', 'INDIAN_SUBCONTINENT', 22.57, 88.36, ARRAY['COMMERCIAL'], ARRAY['River port agency', 'Bulk cargo', 'Port logistics'], 36, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('port_INHAL', 'INHAL', 'Haldia', 'IN', 'India', 'INDIAN_SUBCONTINENT', 22.03, 88.06, ARRAY['COMMERCIAL'], ARRAY['River port agency', 'Bulk cargo', 'Port logistics'], 36, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT ("portCode") DO UPDATE SET
  "portName" = EXCLUDED."portName",
  "country" = EXCLUDED."country",
  "countryName" = EXCLUDED."countryName",
  "region" = EXCLUDED."region",
  "latitude" = EXCLUDED."latitude",
  "longitude" = EXCLUDED."longitude",
  "portType" = EXCLUDED."portType",
  "defaultServices" = EXCLUDED."defaultServices",
  "avgTurnaroundHours" = COALESCE("Port"."avgTurnaroundHours", EXCLUDED."avgTurnaroundHours"),
  "updatedAt" = CURRENT_TIMESTAMP;
